# Generated by Django 3.1.6 on 2021-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_name", models.CharField(max_length=255)),
                ("resource_type", models.CharField(max_length=63)),
                ("encoding", models.CharField(max_length=63)),
                ("resource_file_name", models.CharField(max_length=255)),
                ("ftp_file_path", models.CharField(max_length=1023)),
                ("file_content", models.TextField()),
                ("uploaded_by", models.CharField(max_length=255)),
                ("uploaded_datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
