# Generated by Django 3.1.6 on 2021-02-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("directory_path", models.CharField(max_length=1023)),
                ("file_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=63)),
                ("datatype", models.CharField(max_length=63)),
                ("modification_timestamp", models.IntegerField()),
            ],
        ),
    ]
